package com.liuzhen.string;

/**
 * @class: Cities
 * @description: 
 * @author: L.zhen
 * @date: 2019/10/29 16:03
 */
public class Cities {
	
	public static void main(String[] args) {
		test001();
	}
	
	private static void test001() {
		City[] cities = City.values();
		String[] short4City = new String[cities.length];
		int sc = 0;
		for (int i = 0; i < cities.length; i++) {
			boolean contains = false;
			for (int j = 0; j < i; j++) {
				if (cities[i].shortChar.equals(short4City[j])) {
					contains = true;
					break;
				}
			}
			if (!contains) {
				short4City[sc++] = cities[i].shortChar;
				System.out.println(cities[i].shortChar);
			}
		}
//		for (String s : short4City) {
//			System.out.println(s);
//		}
	}
	
	enum City {
		BEIJING("北京", "BEIJING", "BJ"),
		SHANGHAI("上海", "SHANGHAI", "SH"),
		TIANJIN("天津", "TIANJIN", "TJ"),
		CHONGQING("重庆", "CHONGQING", "ZQ"),
		AKESU("阿克苏", "AKESU", "AKS"),
		AOMEN("澳门", "AOMEN", "AM"),
		ANNING("安宁", "ANNING", "AN"),
		ANQING("安庆", "ANQING", "AQ"),
		ANSHAN("鞍山", "ANSHAN", "AS"),
		ANSHUN("安顺", "ANSHUN", "AS"),
		ANYANG("安阳", "ANYANG", "AY"),
		BAICHENG("白城", "BAICHENG", "BC"),
		BAISHAN("白山", "BAISHAN", "BS"),
		BAIYIN("白银", "BAIYIN", "BY"),
		BENGBU("蚌埠", "BENGBU", "BB"),
		BAODING("保定", "BAODING", "BD"),
		BAOJI("宝鸡", "BAOJI", "BJ"),
		BAOSHAN("保山", "BAOSHAN", "BS"),
		BAZHONG("巴中", "BAZHONG", "BZ"),
		BEIHAI("北海", "BEIHAI", "BH"),
		BENXI("本溪", "BENXI", "BX"),
		BINZHOU("滨州", "BINZHOU", "BZ"),
		BOLE("博乐", "BOLE", "BL"),
		BOZHOU("亳州", "BOZHOU", "BZ"),
		CANGZHOU("沧州", "CANGZHOU", "CZ"),
		CHANGDE("常德", "CHANGDE", "CD"),
		CHANGJI("昌吉", "CHANGJI", "CJ"),
		CHANGSHU("常熟", "CHANGSHU", "CS"),
		CHANGZHOU("常州", "CHANGZHOU", "CZ"),
		CHAOHU("巢湖", "CHAOHU", "CH"),
		CHAOYANG("朝阳", "CHAOYANG", "CY"),
		CHAOZHOU("潮州", "CHAOZHOU", "CZ"),
		CHENGDE("承德", "CHENGDE", "CD"),
		CHENGDU("成都", "CHENGDU", "CD"),
		CHENGGU("城固", "CHENGGU", "CG"),
		CHENZHOU("郴州", "CHENZHOU", "CZ"),
		CHIBI("赤壁", "CHIBI", "CB"),
		CHIFENG("赤峰", "CHIFENG", "CF"),
		CHISHUI("赤水", "CHISHUI", "CS"),
		CHIZHOU("池州", "CHIZHOU", "CZ"),
		CHONGZUO("崇左", "CHONGZUO", "CZ"),
		CHUXIONG("楚雄", "CHUXIONG", "CX"),
		CHUZHOU("滁州", "CHUZHOU", "CZ"),
		CIXI("慈溪", "CIXI", "CX"),
		CONGHUA("从化", "CONGHUA", "CH"),
		DALI("大理", "DALI", "DL"),
		DALIAN("大连", "DALIAN", "DL"),
		DANDONG("丹东", "DANDONG", "DD"),
		DANYANG("丹阳", "DANYANG", "DY"),
		DAQING("大庆", "DAQING", "DQ"),
		DATONG("大同", "DATONG", "DT"),
		DAZHOU("达州", "DAZHOU", "DZ"),
		DEYANG("德阳", "DEYANG", "DY"),
		DEZHOU("德州", "DEZHOU", "DZ"),
		DONGGUAN("东莞", "DONGGUAN", "DG"),
		DONGYANG("东阳", "DONGYANG", "DY"),
		DONGYING("东营", "DONGYING", "DY"),
		DOUYUN("都匀", "DOUYUN", "DY"),
		DUNHUA("敦化", "DUNHUA", "DH"),
		EERDUOSI("鄂尔多斯", "EERDUOSI", "EEDS"),
		ENSHI("恩施", "ENSHI", "ES"),
		FANGCHENGGANG("防城港", "FANGCHENGGANG", "FCG"),
		FEICHENG("肥城", "FEICHENG", "FC"),
		FENGHUA("奉化", "FENGHUA", "FH"),
		FUSHUN("抚顺", "FUSHUN", "FS"),
		FUXIN("阜新", "FUXIN", "FX"),
		FUYANG("阜阳", "FUYANG", "FY"),
		FUYANG1("富阳", "FUYANG1", "FY"),
		FUZHOU("福州", "FUZHOU", "FZ"),
		FUZHOU1("抚州", "FUZHOU1", "FZ"),
		GANYU("赣榆", "GANYU", "GY"),
		GANZHOU("赣州", "GANZHOU", "GZ"),
		GAOMING("高明", "GAOMING", "GM"),
		GAOYOU("高邮", "GAOYOU", "GY"),
		GEERMU("格尔木", "GEERMU", "GEM"),
		GEJIU("个旧", "GEJIU", "GJ"),
		GONGYI("巩义", "GONGYI", "GY"),
		GUANGAN("广安", "GUANGAN", "GA"),
		GUANGYUAN("广元", "GUANGYUAN", "GY"),
		GUANGZHOU("广州", "GUANGZHOU", "GZ"),
		GUBAOTOU("古包头", "GUBAOTOU", "GBT"),
		GUIGANG("贵港", "GUIGANG", "GG"),
		GUILIN("桂林", "GUILIN", "GL"),
		GUIYANG("贵阳", "GUIYANG", "GY"),
		GUYUAN("固原", "GUYUAN", "GY"),
		HAERBIN("哈尔滨", "HAERBIN", "HEB"),
		HAICHENG("海城", "HAICHENG", "HC"),
		HAIKOU("海口", "HAIKOU", "HK"),
		HAIMEN("海门", "HAIMEN", "HM"),
		HAINING("海宁", "HAINING", "HN"),
		HAMI("哈密", "HAMI", "HM"),
		HANDAN("邯郸", "HANDAN", "HD"),
		HANGZHOU("杭州", "HANGZHOU", "HZ"),
		HANZHONG("汉中", "HANZHONG", "HZ"),
		HEBI("鹤壁", "HEBI", "HB"),
		HEFEI("合肥", "HEFEI", "HF"),
		HENGSHUI("衡水", "HENGSHUI", "HS"),
		HENGYANG("衡阳", "HENGYANG", "HY"),
		HETIAN("和田", "HETIAN", "HT"),
		HEYUAN("河源", "HEYUAN", "HY"),
		HEZE("菏泽", "HEZE", "HZ"),
		HUADOU("花都", "HUADOU", "HD"),
		HUAIAN("淮安", "HUAIAN", "HA"),
		HUAIBEI("淮北", "HUAIBEI", "HB"),
		HUAIHUA("怀化", "HUAIHUA", "HH"),
		HUAINAN("淮南", "HUAINAN", "HN"),
		HUANGGANG("黄冈", "HUANGGANG", "HG"),
		HUANGSHAN("黄山", "HUANGSHAN", "HS"),
		HUANGSHI("黄石", "HUANGSHI", "HS"),
		HUHEHAOTE("呼和浩特", "HUHEHAOTE", "HHHT"),
		HUIZHOU("惠州", "HUIZHOU", "HZ"),
		HULUDAO("葫芦岛", "HULUDAO", "HLD"),
		HUZHOU("湖州", "HUZHOU", "HZ"),
		JIAMUSI("佳木斯", "JIAMUSI", "JMS"),
		JIAN("吉安", "JIAN", "JA"),
		JIANGDOU("江都", "JIANGDOU", "JD"),
		JIANGMEN("江门", "JIANGMEN", "JM"),
		JIANGYIN("江阴", "JIANGYIN", "JY"),
		JIAONAN("胶南", "JIAONAN", "JN"),
		JIAOZHOU("胶州", "JIAOZHOU", "JZ"),
		JIAOZUO("焦作", "JIAOZUO", "JZ"),
		JIASHAN("嘉善", "JIASHAN", "JS"),
		JIAXING("嘉兴", "JIAXING", "JX"),
		JIEXIU("介休", "JIEXIU", "JX"),
		JILIN("吉林", "JILIN", "JL"),
		JIMO("即墨", "JIMO", "JM"),
		JINAN("济南", "JINAN", "JN"),
		JINCHENG("晋城", "JINCHENG", "JC"),
		JINGDEZHEN("景德镇", "JINGDEZHEN", "JDZ"),
		JINGHONG("景洪", "JINGHONG", "JH"),
		JINGJIANG("靖江", "JINGJIANG", "JJ"),
		JINGMEN("荆门", "JINGMEN", "JM"),
		JINGZHOU("荆州", "JINGZHOU", "JZ"),
		JINHUA("金华", "JINHUA", "JH"),
		JINING1("集宁", "JINING1", "JN"),
		JINING("济宁", "JINING", "JN"),
		JINJIANG("晋江", "JINJIANG", "JJ"),
		JINTAN("金坛", "JINTAN", "JT"),
		JINZHONG("晋中", "JINZHONG", "JZ"),
		JINZHOU("锦州", "JINZHOU", "JZ"),
		JISHOU("吉首", "JISHOU", "JS"),
		JIUJIANG("九江", "JIUJIANG", "JJ"),
		JIUQUAN("酒泉", "JIUQUAN", "JQ"),
		JIXI("鸡西", "JIXI", "JX"),
		JIYUAN("济源", "JIYUAN", "JY"),
		JURONG("句容", "JURONG", "JR"),
		KAIFENG("开封", "KAIFENG", "KF"),
		KAILI("凯里", "KAILI", "KL"),
		KAIPING("开平", "KAIPING", "KP"),
		KAIYUAN("开远", "KAIYUAN", "KY"),
		KASHEN("喀什", "KASHEN", "KS"),
		KELAMAYI("克拉玛依", "KELAMAYI", "KLMY"),
		KUERLE("库尔勒", "KUERLE", "KEL"),
		KUITUN("奎屯", "KUITUN", "KT"),
		KUNMING("昆明", "KUNMING", "KM"),
		KUNSHAN("昆山", "KUNSHAN", "KS"),
		LAIBIN("来宾", "LAIBIN", "LB"),
		LAIWU("莱芜", "LAIWU", "LW"),
		LAIXI("莱西", "LAIXI", "LX"),
		LAIZHOU("莱州", "LAIZHOU", "LZ"),
		LANGFANG("廊坊", "LANGFANG", "LF"),
		LANZHOU("兰州", "LANZHOU", "LZ"),
		LASA("拉萨", "LASA", "LS"),
		LESHAN("乐山", "LESHAN", "LS"),
		LIANYUNGANG("连云港", "LIANYUNGANG", "LYG"),
		LIAOCHENG("聊城", "LIAOCHENG", "LC"),
		LIAOYANG("辽阳", "LIAOYANG", "LY"),
		LIAOYUAN("辽源", "LIAOYUAN", "LY"),
		LIJIANG("丽江", "LIJIANG", "LJ"),
		LINAN("临安", "LINAN", "LA"),
		LINCANG("临沧", "LINCANG", "LC"),
		LINFEN("临汾", "LINFEN", "LF"),
		LINGBAO("灵宝", "LINGBAO", "LB"),
		LINHE("临河", "LINHE", "LH"),
		LINXIA("临夏", "LINXIA", "LX"),
		LINYI("临沂", "LINYI", "LY"),
		LISHUI("丽水", "LISHUI", "LS"),
		LIUAN("六安", "LIUAN", "LA"),
		LIUPANSHUI("六盘水", "LIUPANSHUI", "LPS"),
		LIUZHOU("柳州", "LIUZHOU", "LZ"),
		LIYANG("溧阳", "LIYANG", "LY"),
		LONGHAI("龙海", "LONGHAI", "LH"),
		LONGYAN("龙岩", "LONGYAN", "LY"),
		LOUDI("娄底", "LOUDI", "LD"),
		LUOHE("漯河", "LUOHE", "LH"),
		LUOYANG("洛阳", "LUOYANG", "LY"),
		LUXI("潞西", "LUXI", "LX"),
		LUZHOU("泸州", "LUZHOU", "LZ"),
		LVLIANG("吕梁", "LVLIANG", "LL"),
		LVSHUN("旅顺", "LVSHUN", "LS"),
		MAANSHAN("马鞍山", "MAANSHAN", "MAS"),
		MAOMING("茂名", "MAOMING", "MM"),
		MEIHEKOU("梅河口", "MEIHEKOU", "MHK"),
		MEISHAN("眉山", "MEISHAN", "MS"),
		MEIZHOU("梅州", "MEIZHOU", "MZ"),
		MIANXIAN("勉县", "MIANXIAN", "MX"),
		MIANYANG("绵阳", "MIANYANG", "MY"),
		MUDANJIANG("牡丹江", "MUDANJIANG", "MDJ"),
		NANAN("南安", "NANAN", "NA"),
		NANCHANG("南昌", "NANCHANG", "NC"),
		NANCHONG("南充", "NANCHONG", "NC"),
		NANJING("南京", "NANJING", "NJ"),
		NANNING("南宁", "NANNING", "NN"),
		NANPING("南平", "NANPING", "NP"),
		NANTONG("南通", "NANTONG", "NT"),
		NANYANG("南阳", "NANYANG", "NY"),
		NEIJIANG("内江", "NEIJIANG", "NJ"),
		NINGBO("宁波", "NINGBO", "NB"),
		NINGDE("宁德", "NINGDE", "ND"),
		PANJIN("盘锦", "PANJIN", "PJ"),
		PANZHIHUA("攀枝花", "PANZHIHUA", "PZH"),
		PENGLAI("蓬莱", "PENGLAI", "PL"),
		PINGDINGSHAN("平顶山", "PINGDINGSHAN", "PDS"),
		PINGDU("平度", "PINGDU", "PD"),
		PINGHU("平湖", "PINGHU", "PH"),
		PINGLIANG("平凉", "PINGLIANG", "PL"),
		PINGXIANG("萍乡", "PINGXIANG", "PX"),
		PULANDIAN("普兰店", "PULANDIAN", "PLD"),
		PUNING("普宁", "PUNING", "PN"),
		PUTIAN("莆田", "PUTIAN", "PT"),
		PUYANG("濮阳", "PUYANG", "PY"),
		QIANNAN("黔南", "QIANNAN", "QN"),
		QIDONG("启东", "QIDONG", "QD"),
		QINGDAO("青岛", "QINGDAO", "QD"),
		QINGYANG("庆阳", "QINGYANG", "QY"),
		QINGYUAN("清远", "QINGYUAN", "QY"),
		QINGZHOU("青州", "QINGZHOU", "QZ"),
		QINHUANGDAO("秦皇岛", "QINHUANGDAO", "QHD"),
		QINZHOU("钦州", "QINZHOU", "QZ"),
		QIONGHAI("琼海", "QIONGHAI", "QH"),
		QIQIHAER("齐齐哈尔", "QIQIHAER", "QQHE"),
		QUANZHOU("泉州", "QUANZHOU", "QZ"),
		QUJING("曲靖", "QUJING", "QJ"),
		QUZHOU("衢州", "QUZHOU", "QZ"),
		RIKAZE("日喀则", "RIKAZE", "RKZ"),
		RIZHAO("日照", "RIZHAO", "RZ"),
		RONGCHENG("荣成", "RONGCHENG", "RC"),
		RUGAO("如皋", "RUGAO", "RG"),
		RUIAN("瑞安", "RUIAN", "RA"),
		RUSHAN("乳山", "RUSHAN", "RS"),
		SANMENXIA("三门峡", "SANMENXIA", "SMX"),
		SANMING("三明", "SANMING", "SM"),
		SANYA("三亚", "SANYA", "SY"),
		XIAMEN("厦门", "XIAMEN", "XM"),
		SHAN("佛山", "SHAN", "FS"),
		SHANGLUO("商洛", "SHANGLUO", "SL"),
		SHANGQIU("商丘", "SHANGQIU", "SQ"),
		SHANGRAO("上饶", "SHANGRAO", "SR"),
		SHANGYU("上虞", "SHANGYU", "SY"),
		SHANTOU("汕头", "SHANTOU", "ST"),
		ANKANG("安康", "ANKANG", "AK"),
		SHAOGUAN("韶关", "SHAOGUAN", "SG"),
		SHAOXING("绍兴", "SHAOXING", "SX"),
		SHAOYANG("邵阳", "SHAOYANG", "SY"),
		SHENYANG("沈阳", "SHENYANG", "SY"),
		SHENZHEN("深圳", "SHENZHEN", "SZ"),
		SHIHEZI("石河子", "SHIHEZI", "SHZ"),
		SHIJIAZHUANG("石家庄", "SHIJIAZHUANG", "SJZ"),
		SHILIN("石林", "SHILIN", "SL"),
		SHISHI("石狮", "SHISHI", "SS"),
		SHIYAN("十堰", "SHIYAN", "SY"),
		SHOUGUANG("寿光", "SHOUGUANG", "SG"),
		SHUANGYASHAN("双鸭山", "SHUANGYASHAN", "SYS"),
		SHUOZHOU("朔州", "SHUOZHOU", "SZ"),
		SHUYANG("沭阳", "SHUYANG", "SY"),
		SIMAO("思茅", "SIMAO", "SM"),
		SIPING("四平", "SIPING", "SP"),
		SONGYUAN("松原", "SONGYUAN", "SY"),
		SUINING("遂宁", "SUINING", "SN"),
		SUIZHOU("随州", "SUIZHOU", "SZ"),
		SUZHOU("苏州", "SUZHOU", "SZ"),
		TACHENG("塔城", "TACHENG", "TC"),
		TAIAN("泰安", "TAIAN", "TA"),
		TAICANG("太仓", "TAICANG", "TC"),
		TAIXING("泰兴", "TAIXING", "TX"),
		TAIYUAN("太原", "TAIYUAN", "TY"),
		TAIZHOU("泰州", "TAIZHOU", "TZ"),
		TAIZHOU1("台州", "TAIZHOU1", "TZ"),
		TANGSHAN("唐山", "TANGSHAN", "TS"),
		TENGCHONG("腾冲", "TENGCHONG", "TC"),
		TENGZHOU("滕州", "TENGZHOU", "TZ"),
		TIANMEN("天门", "TIANMEN", "TM"),
		TIANSHUI("天水", "TIANSHUI", "TS"),
		TIELING("铁岭", "TIELING", "TL"),
		TONGCHUAN("铜川", "TONGCHUAN", "TC"),
		TONGLIAO("通辽", "TONGLIAO", "TL"),
		TONGLING("铜陵", "TONGLING", "TL"),
		TONGLU("桐庐", "TONGLU", "TL"),
		TONGREN("铜仁", "TONGREN", "TR"),
		TONGXIANG("桐乡", "TONGXIANG", "TX"),
		TONGZHOU("通州", "TONGZHOU", "TZ"),
		TONGHUA("通化", "TONGHUA", "TH"),
		TULUFAN("吐鲁番", "TULUFAN", "TLF"),
		WAFANGDIAN("瓦房店", "WAFANGDIAN", "WFD"),
		WEIFANG("潍坊", "WEIFANG", "WF"),
		WEIHAI("威海", "WEIHAI", "WH"),
		WEINAN("渭南", "WEINAN", "WN"),
		WENDENG("文登", "WENDENG", "WD"),
		WENLING("温岭", "WENLING", "WL"),
		WENZHOU("温州", "WENZHOU", "WZ"),
		WUHAI("乌海", "WUHAI", "WH"),
		WUHAN("武汉", "WUHAN", "WH"),
		WUHU("芜湖", "WUHU", "WH"),
		WUJIANG("吴江", "WUJIANG", "WJ"),
		WULANHAOTE("乌兰浩特", "WULANHAOTE", "WLHT"),
		WUWEI("武威", "WUWEI", "WW"),
		WUXI("无锡", "WUXI", "WX"),
		WUZHOU("梧州", "WUZHOU", "WZ"),
		XIAN("西安", "XIAN", "XA"),
		XIANGCHENG("项城", "XIANGCHENG", "XC"),
		XIANGFAN("襄樊", "XIANGFAN", "XF"),
		XIANGGANG("香港", "XIANGGANG", "XG"),
		XIANGGELILA("香格里拉", "XIANGGELILA", "XGLL"),
		XIANGSHAN("象山", "XIANGSHAN", "XS"),
		XIANGTAN("湘潭", "XIANGTAN", "XT"),
		XIANGXIANG("湘乡", "XIANGXIANG", "XX"),
		XIANNING("咸宁", "XIANNING", "XN"),
		XIANTAO("仙桃", "XIANTAO", "XT"),
		XIANYANG("咸阳", "XIANYANG", "XY"),
		XICANG("西藏", "XICANG", "XC"),
		XICHANG("西昌", "XICHANG", "XC"),
		XINGTAI("邢台", "XINGTAI", "XT"),
		XINGYI("兴义", "XINGYI", "XY"),
		XINING("西宁", "XINING", "XN"),
		XINXIANG("新乡", "XINXIANG", "XX"),
		XINYANG("信阳", "XINYANG", "XY"),
		XINYU("新余", "XINYU", "XY"),
		XINZHOU("忻州", "XINZHOU", "XZ"),
		SUQIAN("宿迁", "SUQIAN", "SQ"),
		SUYU("宿豫", "SUYU", "SY"),
		SUZHOU1("宿州", "SUZHOU1", "SZ"),
		XUANCHENG("宣城", "XUANCHENG", "XC"),
		XUCHANG("许昌", "XUCHANG", "XC"),
		XUZHOU("徐州", "XUZHOU", "XZ"),
		YAAN("雅安", "YAAN", "YA"),
		YAKESHI("牙克石", "YAKESHI", "YKS"),
		YANAN("延安", "YANAN", "YA"),
		YANBIAN("延边", "YANBIAN", "YB"),
		YANCHENG("盐城", "YANCHENG", "YC"),
		YANGJIANG("阳江", "YANGJIANG", "YJ"),
		YANGQUAN("阳泉", "YANGQUAN", "YQ"),
		YANGZHOU("扬州", "YANGZHOU", "YZ"),
		YANJI("延吉", "YANJI", "YJ"),
		YANTAI("烟台", "YANTAI", "YT"),
		YANZHOU("兖州", "YANZHOU", "YZ"),
		YIBIN("宜宾", "YIBIN", "YB"),
		YICHANG("宜昌", "YICHANG", "YC"),
		YICHUN("宜春", "YICHUN", "YC"),
		YICHUN1("伊春", "YICHUN1", "YC"),
		YILI("伊犁", "YILI", "YL"),
		YINCHUAN("银川", "YINCHUAN", "YC"),
		YINGKOU("营口", "YINGKOU", "YK"),
		YINGTAN("鹰潭", "YINGTAN", "YT"),
		YINING("伊宁", "YINING", "YN"),
		YIWU("义乌", "YIWU", "YW"),
		YIXING("宜兴", "YIXING", "YX"),
		YIYANG("益阳", "YIYANG", "YY"),
		YONGKANG("永康", "YONGKANG", "YK"),
		YONGZHOU("永州", "YONGZHOU", "YZ"),
		YUEYANG("岳阳", "YUEYANG", "YY"),
		YUHUAN("玉环", "YUHUAN", "YH"),
		YULIN1("榆林", "YULIN1", "YL"),
		YULIN("玉林", "YULIN", "YL"),
		YUNCHENG("运城", "YUNCHENG", "YC"),
		YUXI("玉溪", "YUXI", "YX"),
		YUYAO("余姚", "YUYAO", "YY"),
		ZAOZHUANG("枣庄", "ZAOZHUANG", "ZZ"),
		ZENGCHENG("增城", "ZENGCHENG", "ZC"),
		CHANGCHUN("长春", "CHANGCHUN", "CC"),
		CHANGHAI("长海", "CHANGHAI", "CH"),
		ZHANGJIAGANG("张家港", "ZHANGJIAGANG", "ZJG"),
		ZHANGJIAJIE("张家界", "ZHANGJIAJIE", "ZJJ"),
		ZHANGJIAKOU("张家口", "ZHANGJIAKOU", "ZJK"),
		CHANGLE("长乐", "CHANGLE", "CL"),
		ZHANGQIU("章丘", "ZHANGQIU", "ZQ"),
		CHANGSHA("长沙", "CHANGSHA", "CS"),
		ZHANGYE("张掖", "ZHANGYE", "ZY"),
		CHANGZHI("长治", "CHANGZHI", "CZ"),
		ZHANGZHOU("漳州", "ZHANGZHOU", "ZZ"),
		ZHANJIANG("湛江", "ZHANJIANG", "ZJ"),
		ZHAODONG("肇东", "ZHAODONG", "ZD"),
		ZHAOQING("肇庆", "ZHAOQING", "ZQ"),
		ZHAOTONG("昭通", "ZHAOTONG", "ZT"),
		ZHENGZHOU("郑州", "ZHENGZHOU", "ZZ"),
		ZHENJIANG("镇江", "ZHENJIANG", "ZJ"),
		ZHONGSHAN("中山", "ZHONGSHAN", "ZS"),
		ZHOUKOU("周口", "ZHOUKOU", "ZK"),
		ZHOUSHAN("舟山", "ZHOUSHAN", "ZS"),
		ZHUCHENG("诸城", "ZHUCHENG", "ZC"),
		ZHUHAI("珠海", "ZHUHAI", "ZH"),
		ZHUJI("诸暨", "ZHUJI", "ZJ"),
		ZHUMADIAN("驻马店", "ZHUMADIAN", "ZMD"),
		ZHUZHOU("株洲", "ZHUZHOU", "ZZ"),
		ZIBO("淄博", "ZIBO", "ZB"),
		ZIGONG("自贡", "ZIGONG", "ZG"),
		ZUNYI("遵义", "ZUNYI", "ZY"),
		WULUMUQI("乌鲁木齐", "WULUMUQI", "WLMQ"),
		FUQING("福清", "FUQING", "FQ"),
		EZHOU("鄂州", "EZHOU", "EZ"),
		BAOTOU("包头", "BAOTOU", "BT"),
		XIAOSHAN("萧山", "XIAOSHAN", "XS"),
		XUANHUA("宣化", "XUANHUA", "XH"),
		JIANGYOU("江油", "JIANGYOU", "JY"),
		ZIYANG("资阳", "ZIYANG", "ZY"),
		XINJI("辛集", "XINJI", "XJ"),
		FOSHAN("佛山", "FOSHAN", "FS"),
		WANZHOU("万州", "WANZHOU", "WZ"),
		ZOUCHENG("邹城", "ZOUCHENG", "ZC"),
		SHAOWU("邵武", "SHAOWU", "SW"),
		JIANGYAN("姜堰", "JIANGYAN", "JY"),
		XIANGYIN("湘阴", "XIANGYIN", "XY"),
		SONGJIANG("松江", "SONGJIANG", "SJ"),
		QITAIHE("七台河", "QITAIHE", "QTH"),
		LILING("醴陵", "LILING", "LL"),
		FULING("涪陵", "FULING", "FL"),
		GONGZHULING("公主岭", "GONGZHULING", "GZL"),
		SHEXIAN("歙县", "SHEXIAN", "SX"),
		XINGHUA("兴化", "XINGHUA", "XH"),
		JILONG("基隆", "JILONG", "JL"),
		XINBEI("新北市", "XINBEI", "XB"),
		TAIBEI("台北市", "TAIBEI", "TB"),
		NANTOU("南投县", "NANTOU", "NT"),
		TAINAN("台南县", "TAINAN", "TN"),
		JIAYI("嘉义县", "JIAYI", "JY"),
		TAIZHONG("台中市", "TAIZHONG", "TZ"),
		GAOXIONG("高雄市", "GAOXIONG", "GX"),
		;
		private String name;
		private String fullChar;
		private String shortChar;
		
		public String getName() {
			return name;
		}
		
		public void setName(String name) {
			this.name = name;
		}
		
		public String getFullChar() {
			return fullChar;
		}
		
		public void setFullChar(String fullChar) {
			this.fullChar = fullChar;
		}
		
		public String getShortChar() {
			return shortChar;
		}
		
		public void setShortChar(String shortChar) {
			this.shortChar = shortChar;
		}
		
		City(String name, String fullChar, String shortChar) {
			this.name = name;
			this.fullChar = fullChar;
			this.shortChar = shortChar;
		}
	}
}